import { StyleSheet } from 'react-native';

export const desktopWorkStyles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 8,
  },
  remoteSearch: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: 14,
    paddingHorizontal: 12,
    marginTop: 12,
  },
  remoteSearchInput: {
    flex: 1,
    paddingVertical: 10,
  },
  remoteFilters: {
    gap: 7,
    paddingTop: 9,
    paddingBottom: 4,
  },
  remoteFilter: {
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  headerSlot: {
    width: 44,
  },
  headerCenter: {
    flex: 1,
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
  },
  headerSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  headerBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuBackdrop: {
    flex: 1,
    alignItems: 'flex-end',
    paddingTop: 76,
    paddingRight: 14,
    backgroundColor: 'rgba(0,0,0,0.12)',
  },
  menuCard: {
    width: 300,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 24,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#000000',
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  menuLabel: { fontSize: 12, fontWeight: '600', paddingHorizontal: 12, paddingVertical: 7 },
  menuRow: { flexDirection: 'row', alignItems: 'center', gap: 10, minHeight: 42 },
  menuCheck: { width: 18, alignItems: 'center' },
  menuText: { fontSize: 17, flex: 1 },
  menuDivider: {
    height: StyleSheet.hairlineWidth,
    marginVertical: 8,
    marginHorizontal: 12,
  },
  workspaceBrowser: {
    gap: 4,
  },
  connectedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 24,
  },
  workspaceIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  workspaceText: {
    flex: 1,
    minWidth: 0,
  },
  workspaceTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  workspaceSubtitle: {
    fontSize: 12,
    marginTop: 2,
  },
  sectionTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: '700',
  },
  workspaceSection: {
    gap: 4,
    marginBottom: 8,
  },
  workspaceSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
  },
  connectedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  workspaceGroup: {
    marginBottom: 22,
  },
  workspaceGroupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  workspaceGroupTitle: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  workspaceGroupName: {
    fontSize: 18,
    fontWeight: '700',
  },
  newThreadBtn: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  threadRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minHeight: 44,
    paddingLeft: 0,
    paddingRight: 4,
  },
  nestedThreadRow: {
    paddingLeft: 30,
  },
  threadTitle: {
    flex: 1,
    fontSize: 15,
    lineHeight: 20,
  },
  threadStatus: {
    borderRadius: 8,
    borderWidth: 2,
    height: 16,
    width: 16,
  },
  threadContextBackdrop: {
    flex: 1,
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingTop: 112,
    paddingBottom: 34,
    backgroundColor: 'rgba(0,0,0,0.34)',
  },
  threadPreviewCard: {
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    maxHeight: '58%',
    padding: 20,
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 24,
  },
  threadPreviewTitle: {
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 24,
  },
  threadPreviewBody: {
    fontSize: 15,
    lineHeight: 22,
    marginTop: 14,
  },
  threadPreviewOpen: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'flex-end',
    marginTop: 18,
  },
  threadContextMenu: {
    alignSelf: 'flex-start',
    borderRadius: 22,
    borderWidth: StyleSheet.hairlineWidth,
    minWidth: 250,
    overflow: 'hidden',
    paddingVertical: 8,
    shadowColor: '#000000',
    shadowOpacity: 0.25,
    shadowRadius: 24,
  },
  threadContextAction: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    minHeight: 52,
    paddingHorizontal: 18,
  },
  threadContextActionText: {
    flex: 1,
    fontSize: 17,
    fontWeight: '500',
  },
  threadRenameRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  threadRenameInput: {
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    fontSize: 16,
    minHeight: 42,
    paddingHorizontal: 12,
  },
  threadContextActionIcon: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  emptyThreadText: {
    fontSize: 14,
    paddingLeft: 30,
    paddingTop: 10,
  },
  statusBlock: {
    alignItems: 'center',
    borderRadius: 16,
    gap: 10,
    padding: 18,
  },
  emptyText: {
    fontSize: 14,
    lineHeight: 20,
  },
});
