/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HelpRouteRouteImport } from './routes/help/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SdkIndexRouteImport } from './routes/sdk/index'
import { Route as PricingIndexRouteImport } from './routes/pricing/index'
import { Route as MobileIndexRouteImport } from './routes/mobile/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as EnterpriseIndexRouteImport } from './routes/enterprise/index'
import { Route as DownloadsIndexRouteImport } from './routes/downloads/index'
import { Route as CompanyIndexRouteImport } from './routes/company/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogWebSearchAndCodeExecutionRouteImport } from './routes/blog.web-search-and-code-execution'
import { Route as BlogReviewableMemoryRouteImport } from './routes/blog.reviewable-memory'
import { Route as BlogMediaGenerationRouteImport } from './routes/blog.media-generation'
import { Route as BlogLocalCodingWorkspaceRouteImport } from './routes/blog.local-coding-workspace'
import { Route as BlogIntroducingTaskforceaiRouteImport } from './routes/blog.introducing-taskforceai'
import { Route as BlogGeneratedFilesInChatRouteImport } from './routes/blog.generated-files-in-chat'
import { Route as BlogFinanceWorkflowsAndPlaidRouteImport } from './routes/blog.finance-workflows-and-plaid'
import { Route as BlogDesktopMobilePairingRouteImport } from './routes/blog.desktop-mobile-pairing'
import { Route as BlogComputerUseLocalAndVirtualRouteImport } from './routes/blog.computer-use-local-and-virtual'
import { Route as BlogBenchmarksRouteImport } from './routes/blog.benchmarks'
import { Route as BlogArtifactsAndSitesRouteImport } from './routes/blog.artifacts-and-sites'
import { Route as BlogAgentTeamsEverywhereRouteImport } from './routes/blog.agent-teams-everywhere'
import { Route as HelpCategoryIndexRouteImport } from './routes/help/$category/index'
import { Route as legalTermsIndexRouteImport } from './routes/(legal)/terms/index'
import { Route as legalPrivacyIndexRouteImport } from './routes/(legal)/privacy/index'
import { Route as HelpCategorySlugIndexRouteImport } from './routes/help/$category/$slug/index'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRouteRoute = HelpRouteRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SdkIndexRoute = SdkIndexRouteImport.update({
  id: '/sdk/',
  path: '/sdk/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileIndexRoute = MobileIndexRouteImport.update({
  id: '/mobile/',
  path: '/mobile/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HelpRouteRoute,
} as any)
const EnterpriseIndexRoute = EnterpriseIndexRouteImport.update({
  id: '/enterprise/',
  path: '/enterprise/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsIndexRoute = DownloadsIndexRouteImport.update({
  id: '/downloads/',
  path: '/downloads/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyIndexRoute = CompanyIndexRouteImport.update({
  id: '/company/',
  path: '/company/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWebSearchAndCodeExecutionRoute =
  BlogWebSearchAndCodeExecutionRouteImport.update({
    id: '/blog/web-search-and-code-execution',
    path: '/blog/web-search-and-code-execution',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogReviewableMemoryRoute = BlogReviewableMemoryRouteImport.update({
  id: '/blog/reviewable-memory',
  path: '/blog/reviewable-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogMediaGenerationRoute = BlogMediaGenerationRouteImport.update({
  id: '/blog/media-generation',
  path: '/blog/media-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLocalCodingWorkspaceRoute =
  BlogLocalCodingWorkspaceRouteImport.update({
    id: '/blog/local-coding-workspace',
    path: '/blog/local-coding-workspace',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogIntroducingTaskforceaiRoute =
  BlogIntroducingTaskforceaiRouteImport.update({
    id: '/blog/introducing-taskforceai',
    path: '/blog/introducing-taskforceai',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGeneratedFilesInChatRoute =
  BlogGeneratedFilesInChatRouteImport.update({
    id: '/blog/generated-files-in-chat',
    path: '/blog/generated-files-in-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogFinanceWorkflowsAndPlaidRoute =
  BlogFinanceWorkflowsAndPlaidRouteImport.update({
    id: '/blog/finance-workflows-and-plaid',
    path: '/blog/finance-workflows-and-plaid',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDesktopMobilePairingRoute =
  BlogDesktopMobilePairingRouteImport.update({
    id: '/blog/desktop-mobile-pairing',
    path: '/blog/desktop-mobile-pairing',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogComputerUseLocalAndVirtualRoute =
  BlogComputerUseLocalAndVirtualRouteImport.update({
    id: '/blog/computer-use-local-and-virtual',
    path: '/blog/computer-use-local-and-virtual',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogBenchmarksRoute = BlogBenchmarksRouteImport.update({
  id: '/blog/benchmarks',
  path: '/blog/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogArtifactsAndSitesRoute = BlogArtifactsAndSitesRouteImport.update({
  id: '/blog/artifacts-and-sites',
  path: '/blog/artifacts-and-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAgentTeamsEverywhereRoute =
  BlogAgentTeamsEverywhereRouteImport.update({
    id: '/blog/agent-teams-everywhere',
    path: '/blog/agent-teams-everywhere',
    getParentRoute: () => rootRouteImport,
  } as any)
const HelpCategoryIndexRoute = HelpCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => HelpRouteRoute,
} as any)
const legalTermsIndexRoute = legalTermsIndexRouteImport.update({
  id: '/(legal)/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyIndexRoute = legalPrivacyIndexRouteImport.update({
  id: '/(legal)/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCategorySlugIndexRoute = HelpCategorySlugIndexRouteImport.update({
  id: '/$category/$slug/',
  path: '/$category/$slug/',
  getParentRoute: () => HelpRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/home': typeof HomeRoute
  '/support': typeof SupportRoute
  '/blog/agent-teams-everywhere': typeof BlogAgentTeamsEverywhereRoute
  '/blog/artifacts-and-sites': typeof BlogArtifactsAndSitesRoute
  '/blog/benchmarks': typeof BlogBenchmarksRoute
  '/blog/computer-use-local-and-virtual': typeof BlogComputerUseLocalAndVirtualRoute
  '/blog/desktop-mobile-pairing': typeof BlogDesktopMobilePairingRoute
  '/blog/finance-workflows-and-plaid': typeof BlogFinanceWorkflowsAndPlaidRoute
  '/blog/generated-files-in-chat': typeof BlogGeneratedFilesInChatRoute
  '/blog/introducing-taskforceai': typeof BlogIntroducingTaskforceaiRoute
  '/blog/local-coding-workspace': typeof BlogLocalCodingWorkspaceRoute
  '/blog/media-generation': typeof BlogMediaGenerationRoute
  '/blog/reviewable-memory': typeof BlogReviewableMemoryRoute
  '/blog/web-search-and-code-execution': typeof BlogWebSearchAndCodeExecutionRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/help/': typeof HelpIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/sdk/': typeof SdkIndexRoute
  '/privacy/': typeof legalPrivacyIndexRoute
  '/terms/': typeof legalTermsIndexRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
  '/help/$category/$slug/': typeof HelpCategorySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/home': typeof HomeRoute
  '/support': typeof SupportRoute
  '/blog/agent-teams-everywhere': typeof BlogAgentTeamsEverywhereRoute
  '/blog/artifacts-and-sites': typeof BlogArtifactsAndSitesRoute
  '/blog/benchmarks': typeof BlogBenchmarksRoute
  '/blog/computer-use-local-and-virtual': typeof BlogComputerUseLocalAndVirtualRoute
  '/blog/desktop-mobile-pairing': typeof BlogDesktopMobilePairingRoute
  '/blog/finance-workflows-and-plaid': typeof BlogFinanceWorkflowsAndPlaidRoute
  '/blog/generated-files-in-chat': typeof BlogGeneratedFilesInChatRoute
  '/blog/introducing-taskforceai': typeof BlogIntroducingTaskforceaiRoute
  '/blog/local-coding-workspace': typeof BlogLocalCodingWorkspaceRoute
  '/blog/media-generation': typeof BlogMediaGenerationRoute
  '/blog/reviewable-memory': typeof BlogReviewableMemoryRoute
  '/blog/web-search-and-code-execution': typeof BlogWebSearchAndCodeExecutionRoute
  '/blog': typeof BlogIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/company': typeof CompanyIndexRoute
  '/downloads': typeof DownloadsIndexRoute
  '/enterprise': typeof EnterpriseIndexRoute
  '/help': typeof HelpIndexRoute
  '/mobile': typeof MobileIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/sdk': typeof SdkIndexRoute
  '/privacy': typeof legalPrivacyIndexRoute
  '/terms': typeof legalTermsIndexRoute
  '/help/$category': typeof HelpCategoryIndexRoute
  '/help/$category/$slug': typeof HelpCategorySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/benchmarks': typeof BenchmarksRoute
  '/home': typeof HomeRoute
  '/support': typeof SupportRoute
  '/blog/agent-teams-everywhere': typeof BlogAgentTeamsEverywhereRoute
  '/blog/artifacts-and-sites': typeof BlogArtifactsAndSitesRoute
  '/blog/benchmarks': typeof BlogBenchmarksRoute
  '/blog/computer-use-local-and-virtual': typeof BlogComputerUseLocalAndVirtualRoute
  '/blog/desktop-mobile-pairing': typeof BlogDesktopMobilePairingRoute
  '/blog/finance-workflows-and-plaid': typeof BlogFinanceWorkflowsAndPlaidRoute
  '/blog/generated-files-in-chat': typeof BlogGeneratedFilesInChatRoute
  '/blog/introducing-taskforceai': typeof BlogIntroducingTaskforceaiRoute
  '/blog/local-coding-workspace': typeof BlogLocalCodingWorkspaceRoute
  '/blog/media-generation': typeof BlogMediaGenerationRoute
  '/blog/reviewable-memory': typeof BlogReviewableMemoryRoute
  '/blog/web-search-and-code-execution': typeof BlogWebSearchAndCodeExecutionRoute
  '/blog/': typeof BlogIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/company/': typeof CompanyIndexRoute
  '/downloads/': typeof DownloadsIndexRoute
  '/enterprise/': typeof EnterpriseIndexRoute
  '/help/': typeof HelpIndexRoute
  '/mobile/': typeof MobileIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/sdk/': typeof SdkIndexRoute
  '/(legal)/privacy/': typeof legalPrivacyIndexRoute
  '/(legal)/terms/': typeof legalTermsIndexRoute
  '/help/$category/': typeof HelpCategoryIndexRoute
  '/help/$category/$slug/': typeof HelpCategorySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/about'
    | '/benchmarks'
    | '/home'
    | '/support'
    | '/blog/agent-teams-everywhere'
    | '/blog/artifacts-and-sites'
    | '/blog/benchmarks'
    | '/blog/computer-use-local-and-virtual'
    | '/blog/desktop-mobile-pairing'
    | '/blog/finance-workflows-and-plaid'
    | '/blog/generated-files-in-chat'
    | '/blog/introducing-taskforceai'
    | '/blog/local-coding-workspace'
    | '/blog/media-generation'
    | '/blog/reviewable-memory'
    | '/blog/web-search-and-code-execution'
    | '/blog/'
    | '/changelog/'
    | '/company/'
    | '/downloads/'
    | '/enterprise/'
    | '/help/'
    | '/mobile/'
    | '/pricing/'
    | '/sdk/'
    | '/privacy/'
    | '/terms/'
    | '/help/$category/'
    | '/help/$category/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/benchmarks'
    | '/home'
    | '/support'
    | '/blog/agent-teams-everywhere'
    | '/blog/artifacts-and-sites'
    | '/blog/benchmarks'
    | '/blog/computer-use-local-and-virtual'
    | '/blog/desktop-mobile-pairing'
    | '/blog/finance-workflows-and-plaid'
    | '/blog/generated-files-in-chat'
    | '/blog/introducing-taskforceai'
    | '/blog/local-coding-workspace'
    | '/blog/media-generation'
    | '/blog/reviewable-memory'
    | '/blog/web-search-and-code-execution'
    | '/blog'
    | '/changelog'
    | '/company'
    | '/downloads'
    | '/enterprise'
    | '/help'
    | '/mobile'
    | '/pricing'
    | '/sdk'
    | '/privacy'
    | '/terms'
    | '/help/$category'
    | '/help/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/about'
    | '/benchmarks'
    | '/home'
    | '/support'
    | '/blog/agent-teams-everywhere'
    | '/blog/artifacts-and-sites'
    | '/blog/benchmarks'
    | '/blog/computer-use-local-and-virtual'
    | '/blog/desktop-mobile-pairing'
    | '/blog/finance-workflows-and-plaid'
    | '/blog/generated-files-in-chat'
    | '/blog/introducing-taskforceai'
    | '/blog/local-coding-workspace'
    | '/blog/media-generation'
    | '/blog/reviewable-memory'
    | '/blog/web-search-and-code-execution'
    | '/blog/'
    | '/changelog/'
    | '/company/'
    | '/downloads/'
    | '/enterprise/'
    | '/help/'
    | '/mobile/'
    | '/pricing/'
    | '/sdk/'
    | '/(legal)/privacy/'
    | '/(legal)/terms/'
    | '/help/$category/'
    | '/help/$category/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRouteRoute: typeof HelpRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  BenchmarksRoute: typeof BenchmarksRoute
  HomeRoute: typeof HomeRoute
  SupportRoute: typeof SupportRoute
  BlogAgentTeamsEverywhereRoute: typeof BlogAgentTeamsEverywhereRoute
  BlogArtifactsAndSitesRoute: typeof BlogArtifactsAndSitesRoute
  BlogBenchmarksRoute: typeof BlogBenchmarksRoute
  BlogComputerUseLocalAndVirtualRoute: typeof BlogComputerUseLocalAndVirtualRoute
  BlogDesktopMobilePairingRoute: typeof BlogDesktopMobilePairingRoute
  BlogFinanceWorkflowsAndPlaidRoute: typeof BlogFinanceWorkflowsAndPlaidRoute
  BlogGeneratedFilesInChatRoute: typeof BlogGeneratedFilesInChatRoute
  BlogIntroducingTaskforceaiRoute: typeof BlogIntroducingTaskforceaiRoute
  BlogLocalCodingWorkspaceRoute: typeof BlogLocalCodingWorkspaceRoute
  BlogMediaGenerationRoute: typeof BlogMediaGenerationRoute
  BlogReviewableMemoryRoute: typeof BlogReviewableMemoryRoute
  BlogWebSearchAndCodeExecutionRoute: typeof BlogWebSearchAndCodeExecutionRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  CompanyIndexRoute: typeof CompanyIndexRoute
  DownloadsIndexRoute: typeof DownloadsIndexRoute
  EnterpriseIndexRoute: typeof EnterpriseIndexRoute
  MobileIndexRoute: typeof MobileIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  SdkIndexRoute: typeof SdkIndexRoute
  legalPrivacyIndexRoute: typeof legalPrivacyIndexRoute
  legalTermsIndexRoute: typeof legalTermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sdk/': {
      id: '/sdk/'
      path: '/sdk'
      fullPath: '/sdk/'
      preLoaderRoute: typeof SdkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile/': {
      id: '/mobile/'
      path: '/mobile'
      fullPath: '/mobile/'
      preLoaderRoute: typeof MobileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/enterprise/': {
      id: '/enterprise/'
      path: '/enterprise'
      fullPath: '/enterprise/'
      preLoaderRoute: typeof EnterpriseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads/': {
      id: '/downloads/'
      path: '/downloads'
      fullPath: '/downloads/'
      preLoaderRoute: typeof DownloadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company/': {
      id: '/company/'
      path: '/company'
      fullPath: '/company/'
      preLoaderRoute: typeof CompanyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/web-search-and-code-execution': {
      id: '/blog/web-search-and-code-execution'
      path: '/blog/web-search-and-code-execution'
      fullPath: '/blog/web-search-and-code-execution'
      preLoaderRoute: typeof BlogWebSearchAndCodeExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/reviewable-memory': {
      id: '/blog/reviewable-memory'
      path: '/blog/reviewable-memory'
      fullPath: '/blog/reviewable-memory'
      preLoaderRoute: typeof BlogReviewableMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/media-generation': {
      id: '/blog/media-generation'
      path: '/blog/media-generation'
      fullPath: '/blog/media-generation'
      preLoaderRoute: typeof BlogMediaGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/local-coding-workspace': {
      id: '/blog/local-coding-workspace'
      path: '/blog/local-coding-workspace'
      fullPath: '/blog/local-coding-workspace'
      preLoaderRoute: typeof BlogLocalCodingWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/introducing-taskforceai': {
      id: '/blog/introducing-taskforceai'
      path: '/blog/introducing-taskforceai'
      fullPath: '/blog/introducing-taskforceai'
      preLoaderRoute: typeof BlogIntroducingTaskforceaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/generated-files-in-chat': {
      id: '/blog/generated-files-in-chat'
      path: '/blog/generated-files-in-chat'
      fullPath: '/blog/generated-files-in-chat'
      preLoaderRoute: typeof BlogGeneratedFilesInChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/finance-workflows-and-plaid': {
      id: '/blog/finance-workflows-and-plaid'
      path: '/blog/finance-workflows-and-plaid'
      fullPath: '/blog/finance-workflows-and-plaid'
      preLoaderRoute: typeof BlogFinanceWorkflowsAndPlaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/desktop-mobile-pairing': {
      id: '/blog/desktop-mobile-pairing'
      path: '/blog/desktop-mobile-pairing'
      fullPath: '/blog/desktop-mobile-pairing'
      preLoaderRoute: typeof BlogDesktopMobilePairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/computer-use-local-and-virtual': {
      id: '/blog/computer-use-local-and-virtual'
      path: '/blog/computer-use-local-and-virtual'
      fullPath: '/blog/computer-use-local-and-virtual'
      preLoaderRoute: typeof BlogComputerUseLocalAndVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/benchmarks': {
      id: '/blog/benchmarks'
      path: '/blog/benchmarks'
      fullPath: '/blog/benchmarks'
      preLoaderRoute: typeof BlogBenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/artifacts-and-sites': {
      id: '/blog/artifacts-and-sites'
      path: '/blog/artifacts-and-sites'
      fullPath: '/blog/artifacts-and-sites'
      preLoaderRoute: typeof BlogArtifactsAndSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/agent-teams-everywhere': {
      id: '/blog/agent-teams-everywhere'
      path: '/blog/agent-teams-everywhere'
      fullPath: '/blog/agent-teams-everywhere'
      preLoaderRoute: typeof BlogAgentTeamsEverywhereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category/': {
      id: '/help/$category/'
      path: '/$category'
      fullPath: '/help/$category/'
      preLoaderRoute: typeof HelpCategoryIndexRouteImport
      parentRoute: typeof HelpRouteRoute
    }
    '/(legal)/terms/': {
      id: '/(legal)/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof legalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/privacy/': {
      id: '/(legal)/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof legalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/$category/$slug/': {
      id: '/help/$category/$slug/'
      path: '/$category/$slug'
      fullPath: '/help/$category/$slug/'
      preLoaderRoute: typeof HelpCategorySlugIndexRouteImport
      parentRoute: typeof HelpRouteRoute
    }
  }
}

interface HelpRouteRouteChildren {
  HelpIndexRoute: typeof HelpIndexRoute
  HelpCategoryIndexRoute: typeof HelpCategoryIndexRoute
  HelpCategorySlugIndexRoute: typeof HelpCategorySlugIndexRoute
}

const HelpRouteRouteChildren: HelpRouteRouteChildren = {
  HelpIndexRoute: HelpIndexRoute,
  HelpCategoryIndexRoute: HelpCategoryIndexRoute,
  HelpCategorySlugIndexRoute: HelpCategorySlugIndexRoute,
}

const HelpRouteRouteWithChildren = HelpRouteRoute._addFileChildren(
  HelpRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRouteRoute: HelpRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  BenchmarksRoute: BenchmarksRoute,
  HomeRoute: HomeRoute,
  SupportRoute: SupportRoute,
  BlogAgentTeamsEverywhereRoute: BlogAgentTeamsEverywhereRoute,
  BlogArtifactsAndSitesRoute: BlogArtifactsAndSitesRoute,
  BlogBenchmarksRoute: BlogBenchmarksRoute,
  BlogComputerUseLocalAndVirtualRoute: BlogComputerUseLocalAndVirtualRoute,
  BlogDesktopMobilePairingRoute: BlogDesktopMobilePairingRoute,
  BlogFinanceWorkflowsAndPlaidRoute: BlogFinanceWorkflowsAndPlaidRoute,
  BlogGeneratedFilesInChatRoute: BlogGeneratedFilesInChatRoute,
  BlogIntroducingTaskforceaiRoute: BlogIntroducingTaskforceaiRoute,
  BlogLocalCodingWorkspaceRoute: BlogLocalCodingWorkspaceRoute,
  BlogMediaGenerationRoute: BlogMediaGenerationRoute,
  BlogReviewableMemoryRoute: BlogReviewableMemoryRoute,
  BlogWebSearchAndCodeExecutionRoute: BlogWebSearchAndCodeExecutionRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  CompanyIndexRoute: CompanyIndexRoute,
  DownloadsIndexRoute: DownloadsIndexRoute,
  EnterpriseIndexRoute: EnterpriseIndexRoute,
  MobileIndexRoute: MobileIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  SdkIndexRoute: SdkIndexRoute,
  legalPrivacyIndexRoute: legalPrivacyIndexRoute,
  legalTermsIndexRoute: legalTermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>
  }
}
