/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginMfaRouteImport } from './routes/login/mfa'
import { Route as LoginDeviceRouteImport } from './routes/login/device'
import { Route as ArtifactsArtifactIdRouteImport } from './routes/artifacts.$artifactId'
import { Route as ApiOgRouteImport } from './routes/api/og'
import { Route as ArtifactsPublicTokenRouteImport } from './routes/artifacts.public.$token'

const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginMfaRoute = LoginMfaRouteImport.update({
  id: '/login/mfa',
  path: '/login/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginDeviceRoute = LoginDeviceRouteImport.update({
  id: '/login/device',
  path: '/login/device',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsArtifactIdRoute = ArtifactsArtifactIdRouteImport.update({
  id: '/$artifactId',
  path: '/$artifactId',
  getParentRoute: () => ArtifactsRoute,
} as any)
const ApiOgRoute = ApiOgRouteImport.update({
  id: '/api/og',
  path: '/api/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsPublicTokenRoute = ArtifactsPublicTokenRouteImport.update({
  id: '/public/$token',
  path: '/public/$token',
  getParentRoute: () => ArtifactsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/login/device': typeof LoginDeviceRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/artifacts/public/$token': typeof ArtifactsPublicTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/login/device': typeof LoginDeviceRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login': typeof LoginIndexRoute
  '/artifacts/public/$token': typeof ArtifactsPublicTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRouteWithChildren
  '/api/og': typeof ApiOgRoute
  '/artifacts/$artifactId': typeof ArtifactsArtifactIdRoute
  '/login/device': typeof LoginDeviceRoute
  '/login/mfa': typeof LoginMfaRoute
  '/login/': typeof LoginIndexRoute
  '/artifacts/public/$token': typeof ArtifactsPublicTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/api/og'
    | '/artifacts/$artifactId'
    | '/login/device'
    | '/login/mfa'
    | '/login/'
    | '/artifacts/public/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/api/og'
    | '/artifacts/$artifactId'
    | '/login/device'
    | '/login/mfa'
    | '/login'
    | '/artifacts/public/$token'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/api/og'
    | '/artifacts/$artifactId'
    | '/login/device'
    | '/login/mfa'
    | '/login/'
    | '/artifacts/public/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRouteWithChildren
  ApiOgRoute: typeof ApiOgRoute
  LoginDeviceRoute: typeof LoginDeviceRoute
  LoginMfaRoute: typeof LoginMfaRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/mfa': {
      id: '/login/mfa'
      path: '/login/mfa'
      fullPath: '/login/mfa'
      preLoaderRoute: typeof LoginMfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/device': {
      id: '/login/device'
      path: '/login/device'
      fullPath: '/login/device'
      preLoaderRoute: typeof LoginDeviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$artifactId': {
      id: '/artifacts/$artifactId'
      path: '/$artifactId'
      fullPath: '/artifacts/$artifactId'
      preLoaderRoute: typeof ArtifactsArtifactIdRouteImport
      parentRoute: typeof ArtifactsRoute
    }
    '/api/og': {
      id: '/api/og'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/public/$token': {
      id: '/artifacts/public/$token'
      path: '/public/$token'
      fullPath: '/artifacts/public/$token'
      preLoaderRoute: typeof ArtifactsPublicTokenRouteImport
      parentRoute: typeof ArtifactsRoute
    }
  }
}

interface ArtifactsRouteChildren {
  ArtifactsArtifactIdRoute: typeof ArtifactsArtifactIdRoute
  ArtifactsPublicTokenRoute: typeof ArtifactsPublicTokenRoute
}

const ArtifactsRouteChildren: ArtifactsRouteChildren = {
  ArtifactsArtifactIdRoute: ArtifactsArtifactIdRoute,
  ArtifactsPublicTokenRoute: ArtifactsPublicTokenRoute,
}

const ArtifactsRouteWithChildren = ArtifactsRoute._addFileChildren(
  ArtifactsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRouteWithChildren,
  ApiOgRoute: ApiOgRoute,
  LoginDeviceRoute: LoginDeviceRoute,
  LoginMfaRoute: LoginMfaRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>
  }
}
