import { createRouter } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';

/**
 * TanStack Router configuration.
 *
 * This replaces the previous implicit router setup.
 * The routeTree is auto-generated by the TanStack Start plugin based on files in app/routes/.
 */
export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: 'intent',
  });

  return router;
}

// Register the router for type-safety
declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
