#!/usr/bin/env bun
import {
  buildVercelOutput,
  filesystemRoute,
  handleBuildFailure,
  iconCacheRoute,
  iconResponseHeader,
  reactFunctionPackageJSON,
  responseHeaderRoute,
  route,
  securityHeaderRoute,
  serverlessFallbackRoute,
  staticAssetRoutes,
  temporaryRedirectRoute,
} from '../../../scripts/vercel/build-output';

const marketingRoute = (src: string, dest = src) =>
  route(src, `https://marketing.taskforceai.chat${dest}`);
const docsRoute = (src: string, dest = src) => route(src, `https://docs.taskforceai.chat${dest}`);

buildVercelOutput({
  appName: 'TanStack Start',
  clientCandidates: ['dist/client', '.output/public'],
  serverCandidates: ['.output/server', 'dist/server'],
  outputConfig: {
    version: 3,
    headers: [iconResponseHeader()],
    routes: [
      securityHeaderRoute({ contentSecurityPolicy: false, frameOptions: false }),
      responseHeaderRoute('/((?!api/).*)', {
        'Content-Security-Policy': "frame-ancestors 'none'",
        'X-Frame-Options': 'DENY',
      }),
      ...staticAssetRoutes(),
      iconCacheRoute(),
      temporaryRedirectRoute('/auth/logout', 'https://auth.taskforceai.chat/api/v1/auth/logout'),
      ...[
        ['/sitemap.xml'],
        ['/benchmarks'],
        ['/home'],
        ['/pricing'],
        ['/enterprise'],
        ['/about'],
        ['/downloads'],
        ['/mobile'],
        ['/sdk'],
        ['/terms'],
        ['/privacy'],
        ['/blog'],
        ['/blog/(.*)', '/blog/$1'],
        ['/changelog'],
        ['/changelog/(.*)', '/changelog/$1'],
        ['/company'],
        ['/help'],
        ['/help/(.*)', '/help/$1'],
      ].map(([src, dest]: [string, string?]) => marketingRoute(src, dest)),
      docsRoute('/api-docs'),
      docsRoute('/docs'),
      docsRoute('/docs/(.*)', '/docs/$1'),
      route('/api/auth/(.*)', 'https://auth.taskforceai.chat/api/auth/$1'),
      route('/api/v1/auth/(.*)', 'https://auth.taskforceai.chat/api/v1/auth/$1'),
      route('/api/v1/sync/(.*)', 'https://sync.taskforceai.chat/api/v1/sync/$1'),
      route('/api/v1/payments/(.*)', 'https://billing.taskforceai.chat/api/v1/payments/$1'),
      route('/api/v1/checkout/(.*)', 'https://billing.taskforceai.chat/api/v1/checkout/$1'),
      route('/api/v1/run', 'https://engine.taskforceai.chat/api/v1/run'),
      route('/api/v1/run/(.*)', 'https://engine.taskforceai.chat/api/v1/run/$1'),
      route('/api/v1/integrations/(.*)', 'https://engine.taskforceai.chat/api/v1/integrations/$1'),
      route('/api/v1/stream/(.*)', 'https://engine.taskforceai.chat/api/v1/stream/$1'),
      route('/api/v1/tasks/active', 'https://engine.taskforceai.chat/api/v1/tasks/active'),
      route('/api/v1/tasks/(.*)/cancel', 'https://engine.taskforceai.chat/api/v1/tasks/$1/cancel'),
      route('/api/v1/tasks/(.*)/trace', 'https://engine.taskforceai.chat/api/v1/tasks/$1/trace'),
      route(
        '/api/v1/tasks/(.*)/approve',
        'https://engine.taskforceai.chat/api/v1/tasks/$1/approve'
      ),
      route('/api/v1/developer/(.*)', 'https://developer.taskforceai.chat/api/v1/developer/$1'),
      route('/api/download/(.*)', 'https://api.taskforceai.chat/api/download/$1'),
      route('/api/v1/(.*)', 'https://api.taskforceai.chat/api/v1/$1'),
      route('/api/og', '/index'),
      route('/api/(.*)', 'https://api.taskforceai.chat/api/$1'),
      marketingRoute('/icon-48.webp'),
      filesystemRoute(),
      route('/_build/(.*)', 'https://marketing.taskforceai.chat/_build/$1'),
      route('/assets/(.*)', 'https://marketing.taskforceai.chat/_build/$1'),
      route('/videos/(.*)', 'https://marketing.taskforceai.chat/videos/$1'),
      serverlessFallbackRoute(),
    ],
  },
  functionPackageJSON: reactFunctionPackageJSON(),
}).catch(handleBuildFailure);
