ALTER TABLE webhook_events
ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE webhook_events
ALTER COLUMN processed_at DROP DEFAULT,
ALTER COLUMN processed_at DROP NOT NULL;
