/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as BillingPreferencesRouteImport } from './routes/billing.preferences'
import { Route as BillingPaymentMethodsRouteImport } from './routes/billing.payment-methods'
import { Route as BillingHistoryRouteImport } from './routes/billing.history'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BillingRoute,
} as any)
const BillingPreferencesRoute = BillingPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => BillingRoute,
} as any)
const BillingPaymentMethodsRoute = BillingPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => BillingRoute,
} as any)
const BillingHistoryRoute = BillingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BillingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRouteWithChildren
  '/models': typeof ModelsRoute
  '/usage': typeof UsageRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/payment-methods': typeof BillingPaymentMethodsRoute
  '/billing/preferences': typeof BillingPreferencesRoute
  '/billing/': typeof BillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/models': typeof ModelsRoute
  '/usage': typeof UsageRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/payment-methods': typeof BillingPaymentMethodsRoute
  '/billing/preferences': typeof BillingPreferencesRoute
  '/billing': typeof BillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/billing': typeof BillingRouteWithChildren
  '/models': typeof ModelsRoute
  '/usage': typeof UsageRoute
  '/billing/history': typeof BillingHistoryRoute
  '/billing/payment-methods': typeof BillingPaymentMethodsRoute
  '/billing/preferences': typeof BillingPreferencesRoute
  '/billing/': typeof BillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/billing'
    | '/models'
    | '/usage'
    | '/billing/history'
    | '/billing/payment-methods'
    | '/billing/preferences'
    | '/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/models'
    | '/usage'
    | '/billing/history'
    | '/billing/payment-methods'
    | '/billing/preferences'
    | '/billing'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/billing'
    | '/models'
    | '/usage'
    | '/billing/history'
    | '/billing/payment-methods'
    | '/billing/preferences'
    | '/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  BillingRoute: typeof BillingRouteWithChildren
  ModelsRoute: typeof ModelsRoute
  UsageRoute: typeof UsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/preferences': {
      id: '/billing/preferences'
      path: '/preferences'
      fullPath: '/billing/preferences'
      preLoaderRoute: typeof BillingPreferencesRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/payment-methods': {
      id: '/billing/payment-methods'
      path: '/payment-methods'
      fullPath: '/billing/payment-methods'
      preLoaderRoute: typeof BillingPaymentMethodsRouteImport
      parentRoute: typeof BillingRoute
    }
    '/billing/history': {
      id: '/billing/history'
      path: '/history'
      fullPath: '/billing/history'
      preLoaderRoute: typeof BillingHistoryRouteImport
      parentRoute: typeof BillingRoute
    }
  }
}

interface BillingRouteChildren {
  BillingHistoryRoute: typeof BillingHistoryRoute
  BillingPaymentMethodsRoute: typeof BillingPaymentMethodsRoute
  BillingPreferencesRoute: typeof BillingPreferencesRoute
  BillingIndexRoute: typeof BillingIndexRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingHistoryRoute: BillingHistoryRoute,
  BillingPaymentMethodsRoute: BillingPaymentMethodsRoute,
  BillingPreferencesRoute: BillingPreferencesRoute,
  BillingIndexRoute: BillingIndexRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  BillingRoute: BillingRouteWithChildren,
  ModelsRoute: ModelsRoute,
  UsageRoute: UsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'

import type { createStart } from '@tanstack/react-start'

declare module '@tanstack/react-start' {
  interface Register {
    ssr: true

    router: Awaited<ReturnType<typeof getRouter>>
  }
}
