import { Platform, StyleSheet } from "react-native";
import { colorTokens, spacingTokens } from "@taskforceai/design-tokens";

export const computerTheaterPalette = colorTokens.dark;

export const computerTheaterStyles = StyleSheet.create({
  fullScreenContainer: {
    marginTop: spacingTokens.sm,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "#020617",
    overflow: "hidden",
    height: 400,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
  },
  placeholderText: {
    fontSize: 11,
    color: "rgba(255,255,255,0.3)",
    marginTop: 8,
  },
  screenshotWrapper: {
    flex: 1,
    position: "relative",
  },
  screenshot: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  cursor: {
    position: "absolute",
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#ffffff",
    backgroundColor: "rgba(59, 130, 246, 0.5)",
    marginLeft: -10,
    marginTop: -10,
    alignItems: "center",
    justifyContent: "center",
  },
  cursorInner: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: "#ffffff",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  headerIconContainer: {
    width: 32,
    height: 32,
    borderRadius: 6,
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  modalTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: "#ffffff",
    letterSpacing: 1,
  },
  modalSubtitle: {
    fontSize: 10,
    color: "rgba(255,255,255,0.5)",
  },
  liveFollowBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(59, 130, 246, 0.3)",
  },
  liveFollowDotContainer: {
    width: 6,
    height: 6,
    marginRight: 4,
    alignItems: "center",
    justifyContent: "center",
  },
  liveFollowDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: computerTheaterPalette.primary,
  },
  liveFollowText: {
    fontSize: 9,
    fontWeight: "700",
    color: computerTheaterPalette.primary,
  },
  mainViewport: {
    flex: 1,
    backgroundColor: "#000000",
    padding: 8,
  },
  viewportContainer: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    overflow: "hidden",
    backgroundColor: "#0f172a",
  },
  fullPlaceholder: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  logsContainer: {
    maxHeight: 120,
    backgroundColor: "rgba(15, 23, 42, 0.8)",
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
  },
  logsTitle: {
    fontSize: 9,
    fontWeight: "700",
    color: "rgba(255,255,255,0.4)",
    letterSpacing: 1.2,
    marginBottom: 8,
  },
  logItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  logTimestamp: {
    fontSize: 9,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    color: "rgba(255,255,255,0.3)",
    marginRight: 8,
  },
  logToolName: {
    fontSize: 9,
    fontWeight: "700",
    color: computerTheaterPalette.primary,
    marginRight: 8,
  },
  logArgs: {
    flex: 1,
    fontSize: 10,
    color: "rgba(255,255,255,0.6)",
  },
  activeLogDot: {
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: computerTheaterPalette.primary,
    marginLeft: 6,
  },
});
