export const VERCEL_FUNCTION_PAYLOAD_LIMIT_BYTES = 4_500_000;
export const VERCEL_FUNCTION_SAFE_JSON_PAYLOAD_BYTES = 3 * 1024 * 1024;
export const VERCEL_FUNCTION_MAX_DURATION_SECONDS = 800;
export const VERCEL_FUNCTION_MAX_DURATION_MS = VERCEL_FUNCTION_MAX_DURATION_SECONDS * 1000;
