import { VERCEL_FUNCTION_SAFE_JSON_PAYLOAD_BYTES } from '../config/platform-limits';

export const SYNC_PULL_SAFE_ITEM_LIMIT = 5;
export const SYNC_PULL_SAFE_RESPONSE_BYTES = VERCEL_FUNCTION_SAFE_JSON_PAYLOAD_BYTES;
