use serde_json::Value;

use crate::protocol::{AppRequest, AppResponse, OutgoingMessage};
use crate::runtime::AppRuntime;

use super::responses::{
    error_response, messages_for_success, response_for_notification, runtime_error_response,
};
use super::ServerAction;

pub(super) async fn dispatch(
    request: AppRequest,
    id: Option<Value>,
    is_notification: bool,
    runtime: &mut AppRuntime,
) -> (Vec<OutgoingMessage>, ServerAction) {
    let result = match request {
        AppRequest::Initialize => Ok(runtime.initialize()),
        AppRequest::Ping => Ok(runtime.ping()),
        AppRequest::Shutdown => Ok(runtime.shutdown()),
        AppRequest::ConfigGet => Ok(runtime.config_get()),
        AppRequest::AuthStatus => Ok(runtime.auth_status()),
        AppRequest::AuthLogout => runtime.auth_logout(),
        AppRequest::AuthDeviceStart => runtime.auth_device_start().await,
        AppRequest::AuthDevicePoll(params) => runtime.auth_device_poll(params).await,
        AppRequest::ApiHealth => runtime.api_health().await,
        AppRequest::CommandExecute(params) => runtime.command_execute(params).await,
        AppRequest::QuickModeGet => runtime.quick_mode_get(),
        AppRequest::QuickModeSet(params) => runtime.quick_mode_set(params),
        AppRequest::AutonomousModeGet => runtime.autonomous_mode_get(),
        AppRequest::AutonomousModeSet(params) => runtime.autonomous_mode_set(params),
        AppRequest::ComputerUseModeGet => runtime.computer_use_mode_get(),
        AppRequest::ComputerUseModeSet(params) => runtime.computer_use_mode_set(params),
        AppRequest::GoalGet => runtime.goal_get(),
        AppRequest::GoalSet(params) => runtime.goal_set(params),
        AppRequest::GoalPause => runtime.goal_pause(),
        AppRequest::GoalResume => runtime.goal_resume(),
        AppRequest::GoalClear => runtime.goal_clear(),
        AppRequest::AgentSessionList => runtime.agent_session_list(),
        AppRequest::AgentSessionCreate(params) => runtime.agent_session_create(params),
        AppRequest::AgentSessionGet(params) => runtime.agent_session_get(params),
        AppRequest::AgentSessionPause(params) => runtime.agent_session_pause(params),
        AppRequest::AgentSessionResume(params) => runtime.agent_session_resume(params),
        AppRequest::AgentSessionCancel(params) => runtime.agent_session_cancel(params),
        AppRequest::AgentSessionMessage(params) => runtime.agent_session_message(params),
        AppRequest::AgentSessionFork(params) => runtime.agent_session_fork(params),
        AppRequest::AgentSessionRun(params) => runtime.agent_session_run(params).await,
        AppRequest::ThreadList => runtime.thread_list(),
        AppRequest::ThreadStart(params) => runtime.thread_start(params),
        AppRequest::ThreadResume(params) => runtime.thread_resume(params),
        AppRequest::ThreadArchive(params) => runtime.thread_archive(params),
        AppRequest::ThreadFork(params) => runtime.thread_fork(params),
        AppRequest::TurnStart(params) => runtime.turn_start(params).await,
        AppRequest::TurnSteer(params) => runtime.turn_steer(params),
        AppRequest::TurnInterrupt(params) => runtime.turn_interrupt(params),
        AppRequest::DiagnosticsInspect => runtime.diagnostics_inspect(),
        AppRequest::ChannelList => runtime.channel_list(),
        AppRequest::ChannelAdd(params) => runtime.channel_add(params),
        AppRequest::ChannelDelete(params) => runtime.channel_delete(params),
        AppRequest::ChannelPush(params) => runtime.channel_push(params).await,
        AppRequest::ScheduleList => runtime.schedule_list(),
        AppRequest::ScheduleAdd(params) => runtime.schedule_add(params),
        AppRequest::ScheduleDelete(params) => runtime.schedule_delete(params),
        AppRequest::ScheduleEnable(params) => runtime.schedule_enable(params),
        AppRequest::ScheduleDisable(params) => runtime.schedule_disable(params),
        AppRequest::ScheduleTick(params) => runtime.schedule_tick(params).await,
        AppRequest::WorkflowList => runtime.workflow_list(),
        AppRequest::WorkflowSave(params) => runtime.workflow_save(params),
        AppRequest::WorkflowGet(params) => runtime.workflow_get(params),
        AppRequest::WorkflowDelete(params) => runtime.workflow_delete(params),
        AppRequest::WorkflowRun(params) => runtime.workflow_run(params).await,
        AppRequest::WorkflowRunList => runtime.workflow_run_list(),
        AppRequest::WorkflowRunGet(params) => runtime.workflow_run_get(params),
        AppRequest::WorkflowRunPause(params) => runtime.workflow_run_pause(params),
        AppRequest::WorkflowRunResume(params) => runtime.workflow_run_resume(params),
        AppRequest::WorkflowRunCancel(params) => runtime.workflow_run_cancel(params),
        AppRequest::PetGet => runtime.pet_get(),
        AppRequest::PetSet(params) => runtime.pet_set(params),
        AppRequest::OrchestrationGet => runtime.orchestration_get(),
        AppRequest::OrchestrationSetRole(params) => runtime.orchestration_set_role(params),
        AppRequest::OrchestrationClear => runtime.orchestration_clear(),
        AppRequest::OrchestrationSetBudget(params) => runtime.orchestration_set_budget(params),
        AppRequest::HybridModeGet => runtime.hybrid_mode_get(),
        AppRequest::HybridModeSet(params) => runtime.hybrid_mode_set(params),
        AppRequest::LocalSettingsGet => runtime.local_settings_get(),
        AppRequest::LocalSettingsUpdate(params) => runtime.local_settings_update(params),
        AppRequest::RemoteSettingsCommand(params) => runtime.remote_settings_command(params).await,
        AppRequest::ModelList => runtime.model_list().await,
        AppRequest::ModelSelect(params) => runtime.model_select(params).await,
        AppRequest::ModelReset => runtime.model_reset().await,
        AppRequest::OllamaStatus(params) => runtime.ollama_status(params).await,
        AppRequest::OllamaEnsure(params) => runtime.ollama_ensure(params).await,
        AppRequest::SkillList => runtime.skill_list(),
        AppRequest::PluginList => runtime.plugin_list(),
        AppRequest::PluginSetEnabled(params) => runtime.plugin_set_enabled(params),
        AppRequest::ComputerUseStatus => Ok(runtime.computer_use_status()),
        AppRequest::BrowserStatus => Ok(runtime.browser_status()),
        AppRequest::AttachmentList => Ok(runtime.attachment_list()),
        AppRequest::AttachmentAdd(params) => runtime.attachment_add(params).await,
        AppRequest::AttachmentClear => Ok(runtime.attachment_clear()),
        AppRequest::ConversationList(params) => runtime.conversation_list(params),
        AppRequest::ConversationGet(params) => runtime.conversation_get(params),
        AppRequest::ConversationUpsert(params) => runtime.conversation_upsert(params),
        AppRequest::ConversationReplaceID(params) => runtime.conversation_replace_id(params),
        AppRequest::ConversationDelete(params) => runtime.conversation_delete(params),
        AppRequest::MessageList(params) => runtime.message_list(params),
        AppRequest::MessageGet(params) => runtime.message_get(params),
        AppRequest::MessageUpsert(params) => runtime.message_upsert(params),
        AppRequest::MessageDelete(params) => runtime.message_delete(params),
        AppRequest::PendingChangeList => runtime.pending_change_list(),
        AppRequest::PendingChangeAdd(params) => runtime.pending_change_add(params),
        AppRequest::PendingChangeUpdateData(params) => runtime.pending_change_update_data(params),
        AppRequest::PendingChangeDelete(params) => runtime.pending_change_delete(params),
        AppRequest::PendingChangeClear => runtime.pending_change_clear(),
        AppRequest::PromptQueueList => runtime.prompt_queue_list(),
        AppRequest::PromptQueueAdd(params) => runtime.prompt_queue_add(params).await,
        AppRequest::PromptQueueDelete(params) => runtime.prompt_queue_delete(params),
        AppRequest::PromptQueueClear => runtime.prompt_queue_clear(),
        AppRequest::PromptQueueDispatchAfterResponse(params) => {
            runtime.prompt_queue_dispatch_after_response(params).await
        }
        AppRequest::MetadataGet(params) => runtime.metadata_get(params),
        AppRequest::MetadataSet(params) => runtime.metadata_set(params),
        AppRequest::MetadataClearAll => runtime.metadata_clear_all(),
        AppRequest::SyncStatus => runtime.sync_status(),
        AppRequest::SyncConfigure(params) => runtime.sync_configure(params),
        AppRequest::SyncEnsureDevice => runtime.sync_ensure_device(),
        AppRequest::SyncPull(params) => runtime.sync_pull(params).await,
        AppRequest::SyncPush(params) => runtime.sync_push(params).await,
        AppRequest::DesktopSyncPull(params) => runtime.desktop_sync_pull(params).await,
        AppRequest::DesktopSyncPush(params) => runtime.desktop_sync_push(params).await,
        AppRequest::SyncRealtimePoll(params) => runtime.sync_realtime_poll(params).await,
        AppRequest::UsageSummary => Ok(runtime.usage_summary()),
        AppRequest::StatusSummary => runtime.status_summary(),
        AppRequest::HistoryList(params) => Ok(runtime.history_list(params)),
        AppRequest::RunSearch(params) => Ok(runtime.run_search(params)),
        AppRequest::RunSubmit(params) => runtime.run_submit(params).await,
        AppRequest::RunStatus(params) => runtime.run_status(params),
        AppRequest::RunCancel(params) => runtime.run_cancel(params),
        AppRequest::RunDelete(params) => runtime.run_delete(params),
        AppRequest::PendingPromptList => Ok(runtime.pending_prompt_list()),
        AppRequest::PendingPromptAdd(params) => runtime.pending_prompt_add(params),
        AppRequest::PendingPromptDelete(params) => runtime.pending_prompt_delete(params),
        AppRequest::PendingPromptReplay => runtime.pending_prompt_replay().await,
        AppRequest::ProjectList => runtime.project_list().await,
        AppRequest::ProjectCreate(params) => runtime.project_create(params).await,
        AppRequest::ProjectDelete(params) => runtime.project_delete(params).await,
        AppRequest::ProjectUse(params) => runtime.project_use(params),
        AppRequest::ProjectClear => runtime.project_clear(),
        AppRequest::ContextSummary => Ok(runtime.context_summary()),
        AppRequest::MemorySummary => Ok(runtime.memory_summary()),
        AppRequest::McpList => runtime.mcp_list(),
        AppRequest::McpAdd(params) => runtime.mcp_add(params),
        AppRequest::McpRemove(params) => runtime.mcp_remove(params),
        AppRequest::McpEnable(params) => runtime.mcp_enable(params),
        AppRequest::McpDisable(params) => runtime.mcp_disable(params),
        AppRequest::McpTools(params) => runtime.mcp_tools(params),
        AppRequest::McpAvailable => runtime.mcp_available(),
        AppRequest::McpInspect(params) => runtime.mcp_inspect(params).await,
        AppRequest::McpCallTool(params) => runtime.mcp_call_tool(params).await,
        AppRequest::SyncRun(params) => runtime.sync_realtime_poll(params).await,
        AppRequest::Unsupported => {
            return (
                response_for_notification(
                    is_notification,
                    error_response(id, -32601, "Method not found"),
                ),
                ServerAction::Continue,
            );
        }
    };

    match result {
        Ok(AppResponse::Shutdown(result)) => (
            messages_for_success(id, is_notification, result, Vec::new()),
            ServerAction::Shutdown,
        ),
        Ok(AppResponse::Value(result)) => (
            messages_for_success(id, is_notification, result, Vec::new()),
            ServerAction::Continue,
        ),
        Ok(AppResponse::WithEvents { result, events }) => (
            messages_for_success(id, is_notification, result, events),
            ServerAction::Continue,
        ),
        Err(err) => (
            response_for_notification(is_notification, runtime_error_response(id, err)),
            ServerAction::Continue,
        ),
    }
}
